### ISSUE TITLE
No config yaml! An exampe is created.

### ISSUE THREAD

**Issue by hugokoopmans** [koenvervloesem/ruuvitag-demo#3]
ok I put my ids in tag 1 and tag2 and removed tag 3 and 4...

The bt-gatway complains:

```
pi@raspberrypi:~/ruuvitag-demo/bt-mqtt-gateway $ docker logs bt-mqtt-gateway
There is no config.yaml! An example is created.
There is no config.yaml! An example is created.
There is no config.yaml! An example is created.
There is no config.yaml! An example is created.
There is no config.yaml! An example is created.

```

Seems it cannot find the config file? I know YAML is picky so double checked it seems allright?

```
cat config.yaml 
mqtt:
  host: localhost
  port: 1883
  topic_prefix: bt-mqtt-gateway
  client_id: bt-mqtt-gateway
  availability_topic: availability

manager:
  command_timeout: 30
  workers:
    ruuvitag:
      args:
        devices:
          tag1: F9:B6:F8:D8:28:25
          tag2: CC:CE:58:63:4B:18
        topic_prefix: ruuvitag
      update_interval: 1
```

Any suggestions?

thx hugo
